CREATE TABLE JUGADOR(
ID_JUGADOR NUMERIC(9,0),
NOMBRE VARCHAR(35) NOT NULL,
APELLIDO VARCHAR(35),
FECHA_NAC DATE,
NACIONALIDAD VARCHAR(35),
POSICION VARCHAR(3),
ID_EQUIPO NUMERIC(9,0),
CONSTRAINT PK_JUGADOR PRIMARY KEY(ID_JUGADOR)
);

CREATE TABLE EQUIPO(
ID_EQUIPO NUMERIC(9,0),
NOMBRE VARCHAR(35) NOT NULL,
PAIS VARCHAR(15) NOT NULL,
CIUDAD VARCHAR(15),
ID_LIGA NUMERIC(9,0),
TROFEOS NUMERIC(4,0) NOT NULL,
CONSTRAINT VALID_TROFEOS CHECK(TROFEOS>=0),
CONSTRAINT PK_EQUIPO PRIMARY KEY(ID_EQUIPO)
);

CREATE TABLE JUGADOR_EQUIPO(
ID_JUGADOR NUMERIC(9,0),
ID_EQUIPO NUMERIC(9,0),
NUM_TEMPORADAS NUMERIC(2,0) NOT NULL,
GOLES NUMERIC(4,0),
CONSTRAINT PK_JUGADOR_EQUIPO PRIMARY KEY(ID_JUGADOR,ID_EQUIPO),
CONSTRAINT VALID_NUMTEMPORADAS CHECK(NUM_TEMPORADAS>0),
CONSTRAINT VALID_GOLES CHECK (GOLES>0)
);

CREATE TABLE LIGA(
ID_LIGA NUMERIC(9,0),
NOMBRE VARCHAR(35) NOT NULL,
REGION VARCHAR(10) NOT NULL, 
JORNADAS NUMERIC(2,0) NOT NULL,
CONSTRAINT VALID_JORNADAS CHECK(JORNADAS>=0),
CONSTRAINT PK_LIGA PRIMARY KEY(ID_LIGA)
);


CREATE TABLE TEMPORADA(
ID_LIGA NUMERIC(9,0),
GOLES_TOTALES NUMERIC(4,0),
AÑO NUMERIC(4,0),
CONSTRAINT VALID_GOLESTOT CHECK(GOLES_TOTALES>=0),
CONSTRAINT VALID_AÑO CHECK(AÑO>=1918),
CONSTRAINT PK_TEMPORADA PRIMARY KEY(ID_LIGA,AÑO)
);



ALTER TABLE JUGADOR ADD CONSTRAINT JUGADOR_IDEQUIPO_FKEY FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPO (ID_EQUIPO) ON DELETE SET NULL;

ALTER TABLE JUGADOR_EQUIPO ADD CONSTRAINT JUGADOREQUIPO_IDEQUIPO_FKEY FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPO (ID_EQUIPO);
ALTER TABLE JUGADOR_EQUIPO ADD CONSTRAINT JUGADOREQUIPO_IDJUGADOR_FKEY FOREIGN KEY (ID_JUGADOR) REFERENCES JUGADOR (ID_JUGADOR);

ALTER TABLE EQUIPO ADD CONSTRAINT EQUIPO_IDLIGA_FKEY FOREIGN KEY (ID_LIGA) REFERENCES LIGA (ID_LIGA) ON DELETE SET NULL;


ALTER TABLE TEMPORADA ADD CONSTRAINT TEMPORADA_IDLIGA_FKEY FOREIGN KEY (ID_LIGA) REFERENCES LIGA (ID_LIGA) ON DELETE CASCADE;



